#!/bin/bash


# IF this is going to be a Virt...

# 1. Set up virtualbox to have four active network adapters
# 2. Set up virtualbox to have four active serial ports
# 3. Set ram to your liking for now
# 4. Set storage to 80 GB or so..
# 5. Boot the virt using the Fedora xfce live cd
# 6. Choose "Install to hard disk"
# 7. Partition as you like
# 8. Encrypt the disk
# 9. Create username for yourself, preferably your ldap user name
# 10. Check "make this user an admin"
# 11. Set root pw.
# 12. Reboot after completion of installation.

# 1. Choose to use default xfce initial config
# 2. Disconnect three of the network interfaces, except for the one set to NAT# 3. yum -y update
# 4. restart system
# 5. yum -y install git
# 6. create directory ~/GitRepos
# 7. 



